const fs = require('node:fs');
const assert = require('node:assert/strict');
const htmlFiles = fs.readdirSync('.').filter(file => file.endsWith('.html'));
const read = file => fs.readFileSync(file, 'utf8');
const allPublicText = [...htmlFiles, 'robots.txt', 'sitemap.xml', 'app.js', 'styles.css'].map(read).join('\n');
assert(!allPublicText.includes('zxj088.github.io/subset'), 'obsolete Pages URL remains');
assert(!allPublicText.includes('github.com/zxj088/subset'), 'obsolete repository URL remains');
assert(!allPublicText.includes('github.com/') && !allPublicText.includes('GitHub'), 'repository hosting must not be shown on the public site');
assert(!allPublicText.includes('brand-mark">U'), 'logo-like U mark remains');
assert(!read('styles.css').includes('.brand-mark{'), 'legacy logo CSS remains');
assert(!allPublicText.includes('fonts.googleapis.com'), 'runtime Google Fonts dependency remains');
for (const required of ['index.html','404.html','legal.html','subset-098-rag.html','evidence-subset-098.html','rights-policy.json']) assert(fs.existsSync(required), `${required} is missing`);
const evidencePages = htmlFiles.filter(file => file.startsWith('evidence-'));
assert.deepEqual(evidencePages, ['evidence-subset-098.html'], 'only current-scope evidence may be public');
assert(!htmlFiles.some(file => file.startsWith('unisig-corpus-') || file.startsWith('subset-098-corpus')), 'machine corpora must not be public artifacts');
const homepage = read('index.html');
assert(homepage.includes('Rail Specifications Evidence Search') && homepage.includes('subset-098-rag.html') && homepage.includes('legal.html') && homepage.includes('rel="canonical"'));
assert(homepage.includes('How to use this site.') && homepage.includes('homeQuestion'), 'homepage must provide a new-user path');
assert(read('app.js').includes('Catalogue only') && read('app.js').includes('Search evidence'), 'catalogue must disclose per-document search availability');
const assistant = read('subset-098-rag.html');
assert(assistant.includes('aria-live="polite"') && read('subset-098-rag.js').includes('Copy citation') && assistant.includes('No institutional endorsement'));
assert(read('subset-098-rag.js').includes('verifiedBundle'), 'verified clause bundles must not be truncated as ordinary context');
const sitemap = read('sitemap.xml');
assert(sitemap.includes('RAG-UNISIG-SUBSET') && !sitemap.includes('evidence-') && !sitemap.includes('corpus'), 'sitemap exposes obsolete or machine pages');
const rights = JSON.parse(read('rights-policy.json'));
assert.equal(rights.default, 'catalogue-only-pending-review');
assert.equal(rights.searchable.length, 1);
assert.equal(rights.searchable[0].reference, 'SUBSET-098');
console.log(`Production safeguards passed across ${htmlFiles.length} public HTML files.`);
